version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vpn_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - VPN_HOST=${VPN_HOST}
      - VPN_PORT=${VPN_PORT}
      - VPN_CLIENT_DIR=/etc/openvpn/clients
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - certs_data:/etc/openvpn/clients
    depends_on:
      - redis
    networks:
      - vpn_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - VPN_HOST=${VPN_HOST}
      - VPN_PORT=${VPN_PORT}
      - VPN_CLIENT_DIR=/etc/openvpn/clients
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - certs_data:/etc/openvpn/clients
    depends_on:
      - redis
      - web
    networks:
      - vpn_network

  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    ports:
      - "5555:5555"
    command: celery -A celery_config flower --port=5555
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker
    networks:
      - vpn_network

volumes:
  redis_data:
  certs_data:

networks:
  vpn_network:
    driver: bridge 