global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vpn_service'
    static_configs:
      - targets: ['web:5000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker:5555']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scheme: 'http' 